/**
 * Right-click / long-press on a [[Pane]] tab raises the [[Context Menu]] for it.
 *
 * Dockview renders the tab strip, so there is no component of ours to hang a handler on.
 * This delegates from the dockview container and resolves the event back to a panel — the
 * same approach `tab-strip-scrollbar.ts` already takes to that DOM, rather than a second
 * invented one.
 *
 * **Every** tab gets a menu, not only document tabs. Favouriting or renaming an [[Asset]] or
 * All Documents tab is still meaningless — those rows carry a `when` and stay away — but the
 * tab-management rows (close others, close to the right) apply to any tab, and they are the
 * reason a non-document tab has a menu at all. A tab that resolves to no panel gets nothing,
 * and dockview's own menu is suppressed either way so there is one menu, styled like the rest.
 */

import { openContextMenu, type ContextMenuTarget } from '$lib/surface'

const LONG_PRESS_MS = 500
const LONG_PRESS_SLOP_PX = 10

/**
 * Resolves a right-clicked/long-pressed tab element to the [[Context Menu]] target it stands
 * for, or null when it resolves to no panel at all.
 *
 * The tab DOM element itself, not just its label: dockview puts no panel id on the tab element,
 * but the adapter can still walk up to the enclosing Pane group and search only ITS panels —
 * scoping the match to the Pane the click actually happened in, so two tabs sharing a visible
 * label in different Panes (an Asset tab before its title resolves, a `forceNew` duplicate) can
 * never resolve to the wrong Pane's panel.
 */
export type TargetForTab = (tab: HTMLElement) => ContextMenuTarget | null

/** The label dockview renders inside a tab. */
export function labelOf(tab: HTMLElement): string {
    return (tab.querySelector('.dv-default-tab-content')?.textContent ?? tab.textContent ?? '').trim()
}

export function installTabContextMenu(container: HTMLElement, targetForTab: TargetForTab): () => void {
    let timer: ReturnType<typeof setTimeout> | undefined
    let start: { x: number; y: number } | null = null
    let fired = false

    const clear = () => {
        if (timer) clearTimeout(timer)
        timer = undefined
        start = null
    }

    const tabFrom = (event: Event): HTMLElement | null =>
        (event.target as HTMLElement | null)?.closest?.('.dv-tab') ?? null

    const onContextMenu = (event: MouseEvent) => {
        const tab = tabFrom(event)
        if (!tab) return
        // Suppressed even when we have nothing to show, so dockview's own menu never appears
        // beside ours on some tabs and not others.
        event.preventDefault()
        const target = targetForTab(tab)
        if (!target) return
        openContextMenu(target, event.clientX, event.clientY)
    }

    const onPointerDown = (event: PointerEvent) => {
        if (event.pointerType !== 'touch') return
        const tab = tabFrom(event)
        if (!tab) return
        const target = targetForTab(tab)
        if (!target) return
        fired = false
        start = { x: event.clientX, y: event.clientY }
        timer = setTimeout(() => {
            fired = true
            clear()
            openContextMenu(target, event.clientX, event.clientY)
        }, LONG_PRESS_MS)
    }

    const onPointerMove = (event: PointerEvent) => {
        if (!start) return
        // A drag is a tab reorder or a strip scroll, not a press.
        if (Math.hypot(event.clientX - start.x, event.clientY - start.y) > LONG_PRESS_SLOP_PX) clear()
    }

    // Capture phase: dockview activates a tab on click, so the click generated by a long
    // press has to be swallowed before it reaches dockview or the tab switches under the menu.
    const onClick = (event: MouseEvent) => {
        if (!fired) return
        fired = false
        event.preventDefault()
        event.stopPropagation()
    }

    container.addEventListener('contextmenu', onContextMenu)
    container.addEventListener('pointerdown', onPointerDown)
    container.addEventListener('pointermove', onPointerMove)
    container.addEventListener('pointerup', clear)
    container.addEventListener('pointercancel', clear)
    container.addEventListener('click', onClick, true)

    return () => {
        clear()
        container.removeEventListener('contextmenu', onContextMenu)
        container.removeEventListener('pointerdown', onPointerDown)
        container.removeEventListener('pointermove', onPointerMove)
        container.removeEventListener('pointerup', clear)
        container.removeEventListener('pointercancel', clear)
        container.removeEventListener('click', onClick, true)
    }
}
