/**
 * The files a site folder is seeded with once and never rewritten (ADR 0082): the deploy
 * workflow for GitHub Pages, the Workers configuration, a README and a .gitignore, plus the
 * folder's AGENTS.md, whose managed section is rewritten every publish while the user's own
 * text outside it is kept (the ADR 0070 mechanism). Pure text; the host decides what exists.
 */

import type { Publication } from './types'

export const PAGES_WORKFLOW_PATH = '.github/workflows/pages.yaml'
export const WRANGLER_PATH = 'wrangler.jsonc'
export const ASSETS_IGNORE_PATH = '.assetsignore'
export const README_PATH = 'README.md'
export const GITIGNORE_PATH = '.gitignore'
export const AGENTS_PATH = 'AGENTS.md'

/** Files written when absent and left alone afterwards. */
export function seededFiles(publication: Publication): Map<string, string> {
    return new Map([
        [
            PAGES_WORKFLOW_PATH,
            `# Publishes this folder to GitHub Pages as it is: the site is already built by EtherPK,
# so there is no build step. In the repository's Settings → Pages, set the source to
# "GitHub Actions" once; every push to main then deploys.
name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@v4
`,
        ],
        [
            WRANGLER_PATH,
            `// Cloudflare Workers with static assets (Cloudflare's successor to Pages for new sites).
// Deploy with \`npx wrangler deploy\`, or connect the repository in the dashboard under
// Workers → Create → Import a repository and leave the build command empty. The Worker is
// named after the publication; Cloudflare warns when this name and the Worker's differ.
{
    "name": "${publication.id}",
    "compatibility_date": "2026-01-01",
    "assets": {
        "directory": ".",
        "html_handling": "auto-trailing-slash",
        "not_found_handling": "404-page"
    }
}
`,
        ],
        [
            README_PATH,
            `# ${publication.name}

This folder is a website published by [EtherPK](https://etherpk.com) from the publication
\`${publication.id}\`. Every file in it except \`CNAME\` and \`robots.txt\` is regenerated on each
publish, so edit the notes, the publication page, its include pages and its theme in EtherPK,
not here.

- Preview: open \`index.html\` in a browser; search works from disk too.
- GitHub Pages: push this folder to a repository and set Settings → Pages → Source to
  "GitHub Actions"; \`.github/workflows/pages.yaml\` deploys every push to \`main\`.
- Cloudflare: \`npx wrangler deploy\` uses \`wrangler.jsonc\`, or connect the repository in the
  Workers dashboard with no build command.
- Netlify, GitLab Pages, Vercel, S3 or your own server: the folder is plain files, so any of
  them serves it as it is. Step by step for each: https://docs.etherpk.com/hosting-a-published-site
`,
        ],
        [GITIGNORE_PATH, `.DS_Store\nThumbs.db\n`],
        // Wrangler serves every file under the assets directory, which here is the folder itself:
        // without this, a folder that is also a git repository served its .git to the world.
        [
            ASSETS_IGNORE_PATH,
            `# Files in this folder that are not part of the website, kept out of the Worker's assets.
# Written once by EtherPK; yours to edit.
.git
.github
.gitignore
.assetsignore
.nojekyll
wrangler.jsonc
AGENTS.md
README.md
etherpk-publish.json
`,
        ],
    ])
}

const AGENTS_START = '<!-- etherpk:start -->'
const AGENTS_END = '<!-- etherpk:end -->'

function managedSection(publication: Publication): string {
    return `${AGENTS_START}
## EtherPK published site

This folder is a website generated by [EtherPK](https://etherpk.com) from the publication
\`${publication.id}\` ("${publication.name}"). It is **output**: every file except \`CNAME\`,
\`robots.txt\` and the text outside this section of \`AGENTS.md\` is rewritten on each publish
and files that are no longer produced are deleted.

- Do not edit the HTML, the assets or \`theme/\` here; the change is lost on the next publish.
- Content changes are made to the documents in EtherPK. A document is published when its
  frontmatter says \`public: true\` and names this publication in \`publications: [${publication.id}]\`
  (unless the publication takes every public document).
- The navigation is the outline of the publication page in EtherPK; the theme and the include
  slots (head, logo, header, footer, before-content, after-content, scripts, styles) are chosen
  and edited there too, in the Publish settings and the Theme editor.
- \`index.html\` opens from disk for a preview. \`.github/workflows/pages.yaml\` deploys the folder
  to GitHub Pages; \`wrangler.jsonc\` deploys it to Cloudflare Workers; any static host serves it
  as it is (https://docs.etherpk.com/hosting-a-published-site).

This section is rewritten by EtherPK on every publish. Put your own notes above or below it.
${AGENTS_END}
`
}

/** The folder's AGENTS.md with the managed section replaced or added, the user's text kept. */
export function agentsMdWithManagedSection(existing: string | null, publication: Publication): string {
    const section = managedSection(publication)
    if (existing === null || existing.trim() === '') return section
    const start = existing.indexOf(AGENTS_START)
    const end = existing.indexOf(AGENTS_END)
    if (start !== -1 && end !== -1 && end > start) {
        return existing.slice(0, start) + section.trimEnd() + existing.slice(end + AGENTS_END.length)
    }
    return `${existing.trimEnd()}\n\n${section}`
}
